### PR TITLE
Addition and Fixes of Tweet Analytics

### PR DESCRIPTION
**Pull request by Engineering-Robert**
Fixed a bunch of issues related to how tweet counts were being displayed on the app. I've also modified the styling of the analytics page.

Commits from the mobile-responsiveness branch are also in this one. Not sure if I'm using a proper Git workflow, so let me know if there is anything I should change in terms of my commits/branches @vinitkumar.

### CODE REVIEW

**Comment by vinitkumar** [comment]
@Engineering-Robert I will try and outline a workflow for you. 

Always use a branch for a single thing. For eg., if you want to fix responsiveness create a branch

fix/mobile-responsiveness and work on all commit related to responsiveness.

Next, we if you wanted to work about tweet analytics, create a fresh branch from `develop` with that name and not from `fix/mobile-responsiveness` because it will contain commit from fix/mobile-responsiveness which we don't require in this branch

**Comment by Engineering-Robert** [comment]
Ok, so we should have a "develop" branch from which we create "feature" branches? Once a feature branch is complete, we merge it into the "develop" branch?

**Comment by vinitkumar** [comment]
@Engineering-Robert Yes, that's how it should be done always. Even though we don't have develop here. We can consider master to be same. 

So,  create the branch from master, do your work, merge the code and for any new work create the branch from master again.

**Comment by Engineering-Robert** [comment]
Ok got it!

**Pull request merged**
