### PR TITLE
Dockerize server (#249, #236)

### PR DESCRIPTION
**Pull request by irsol**
## Description
App and MongoDB can run as Docker containers.

## Issue Addressed 

- Issue number #249 

- Issue number #236 

## Additionally
Upgraded Node version to **12.0.0**.

---
This change is [Reviewable](https://reviewable.io/reviews/vinitkumar/node-twitter/251)

### CODE REVIEW

**Comment by irsol** [comment]
> > _[Reviewable](https://reviewable.io/reviews/vinitkumar/node-twitter/251)_ status: all files reviewed, 10 unresolved discussions (waiting on @irsol)
> 
> _[server.js, line 16 at r1](https://reviewable.io/reviews/vinitkumar/node-twitter/251#-LsxQCwA61J8iEjW7mbE:-LsxQCwA61J8iEjW7mbF:b5mgmf7) ([raw file](https://github.com/vinitkumar/node-twitter/blob/edde5754cbda63815756c948608260252db3c2a4/server.js#L16)):_
> 
> > ```js
> > app.use(cookieParser("super55"));
> > app.use(cookieSession({
> > ```
> 
> See comment about `SECRET` how to solve problem that will appear once you remove those lines

Created new issue #252 [.](https://github.com/vinitkumar/node-twitter/issues/252)

**Comment by irsol** [comment]
> > _[Reviewable](https://reviewable.io/reviews/vinitkumar/node-twitter/251)_ status: all files reviewed, 9 unresolved discussions (waiting on @irsol)
> 
> _[Dockerfile, line 7 at r1](https://reviewable.io/reviews/vinitkumar/node-twitter/251#-LsxOJ0v4c-Uf-yVLOfb:-LsxOJ0v4c-Uf-yVLOfc:bbm1v5) ([raw file](https://github.com/vinitkumar/node-twitter/blob/edde5754cbda63815756c948608260252db3c2a4/Dockerfile#L7)):_
> 
> > ```dockerfile
> > COPY package*.json ./
> > RUN npm install
> > ENV SECRET='abadjadjadja1223232412424'
> > ```
> 
> When I run the server without Docker it is missing `SECRET` variable (see file `expess.js` where it is used) and I get an error **Error: secret option required for sessions**. You probably need to define this variable in .env file

Created new issue #252 [.](https://github.com/vinitkumar/node-twitter/issues/252)

**Comment by irsol** [comment]
> environment variable

Renamed env variables.

**Comment by vinitkumar** [comment]
@irsol @sash-ko Sorry guys! I have been busy so I didn't look into the notifications. Posting some comments on the PR. @irsol if you able to resolve this, I will be more than happy to merge this PR.

**Pull request merged**
