### PR TITLE
Feature/find hashtag

### PR DESCRIPTION
**Pull request by irsol**
## Description

Implemented a new endpoint that allows search tweets by hashtags:

`http://localhost:3000/tweets/hashtag/<tag>`

After calling this endpoint renders a normal page but with filtered tweets.

---
This change is [Reviewable](https://reviewable.io/reviews/vinitkumar/node-twitter/276)

### CODE REVIEW

**Comment by vinitkumar** [comment]
@irsol This looks good to me. Can you please work on the render part in the tweet, so that `#tag`, is converted to a link that takes to the page for the tags.

**Comment by irsol** [comment]
@vinitkumar yes, no problem. I'll make separate feature/branch for to highlight hashtags and convert it to a link. Is it ok for you?

**Comment by vinitkumar** [comment]
@irsol If you want, you can do it here only as this branch and that feature can be done in the same branch. Let's keep it simple and do it in this branch only.

**Comment by irsol** [comment]
@vinitkumar ok, I'll do it in this branch.

**Comment by vinitkumar** [comment]
@irsol Any ETA on this?

**Comment by irsol** [comment]
@vinitkumar sorry Christmas holidays.🎄I try to finish it in the next 2 days.

**Comment by vinitkumar** [comment]
@irsol No worries. Merry Christmas and Happy new year to you. Do it after the holidays. Enjoy 🎄

**Comment by irsol** [comment]
@vinitkumar thanks, you too!

**Comment by vinitkumar** [comment]
How much work is remaining in this feature?

**Comment by irsol** [comment]
@vinitkumar all done! You can merge it. Tags work!

**Comment by vinitkumar** [comment]
@irsol Your code had a minor bug, where you change the name of the method in the model but forgot to rename it in controllers. My last commit https://github.com/vinitkumar/node-twitter/pull/276/commits/e323d4ea9a14c71d1d6960e7c3849b82d0d36770 fixes that. Now, it's good to go! 

Very nice work :+1:

**Comment by irsol** [comment]
@vinitkumar thank you for fixing this bag.🍻

**Pull request merged**
