### PR TITLE
Css classes refactor

### LINKED ISSUE #114: Display an individual tweet as a modal
Currently the app redirects the user to a seperate page. To view an individual tweet, you must click on the date the tweet was written.

### PR DESCRIPTION
**Pull request by Engineering-Robert**
Fixes #114 and #162

---
This change is [Reviewable](https://reviewable.io/reviews/vinitkumar/node-twitter/171)

### CODE REVIEW

**Comment by vinitkumar** [comment]
@Engineering-Robert Would really appreciate if you can keep the PRs smaller. Smaller PRs are easier to review and more possible to spot bugs that way. Also, different issues deserve different PRs as they keep the context clear.

Another thing, I am travelling today and tomorrow so most probably be online only on Sunday.

**Comment by Engineering-Robert** [comment]
Ya, this one got quite lengthy, my apologies. However, I did want to get all this work within this pull request since I wanted you to merge all of this today. The alternative would have been to do half the work, make a PR, wait for you to merge, do the other work, make another PR, have you merge the PR.
I see two possible solutions to the above problem, and that would be to either merge the smaller PRs myself, or I can make branches on a forked repository, merge PRs into master on the fork along with making PRs from my forked branch to the original master branch.

**Comment by Engineering-Robert** [comment]
I did not mean to merge this. I thought I was on my forked repository! I'm trying to revert it right now.

**Comment by vinitkumar** [comment]
Well. I think I am only interested in reviewing breaking changes. As long
as you are doing think that are an enhancement. I am pretty cool with you
merging it. Also, even when you are merging it. Try and keep your PR small.
It helps to debug things in case something brakes. Also, bi changes must be
done in phases. So plan your work accordingly. It might sound tedious. But
believe me, it helps a lot in maintaining the software and finding bugs
quickly.

On 20-Oct-2017 11:19 AM, "Robert Cooper" <notifications@github.com> wrote:

Ya, this one got quite lengthy, my apologies. However, I did want to get
all this work within this pull request since I wanted you to merge all of
this today. The alternative would have been to do half the work, make a PR,
wait for you to merge, do the other work, make another PR, have you merge
the PR.
I see two possible solutions to the above problem, and that would be to
either merge the smaller PRs myself, or I can make branches on a forked
repository, merge PRs into master on the fork along with making PRs from my
forked branch to the original master branch.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/vinitkumar/node-twitter/pull/171#issuecomment-338112201>,
or mute the thread

**Pull request merged**
