### PR TITLE
Dark Profile UI

### PR DESCRIPTION
**Pull request by Engineering-Robert**
I've added some styling to the application that gives it a dark UI look similar to what Twitter has available. I can't get the tweets to work locally yet, so not all elements have the styling applied to them yet.
image

### CODE REVIEW

**Comment by vinitkumar** [comment]
@Engineering-Robert First of all, this is such an amazing work 🚀 . Thanks for contributing. It looks mostly awesome. There are some places that need to be updated as per the new design.

Please see these screenshots.

screenshot 2017-09-20 at 11 03 36 am
screenshot 2017-09-20 at 11 03 46 am
screenshot 2017-09-20 at 11 03 55 am

If you are able to fix these issues. I would be very happy to merge it and release it as well.

Also, about the issue with you able to create tweets, please check my comments here: 

https://github.com/vinitkumar/node-twitter/issues/102#issuecomment-330749648

**Comment by Engineering-Robert** [comment]
@vinitkumar Thanks for the feedback. I've made some more changes to the portions that you highlighted. I had to use a workaround to get the tweets to work for me, so I'm not sure if the code will work on the production server. I mentioned what code I changed in a comment here: #102 

Here are some screenshots of what I've updated:

image

image

image

image

**Comment by vinitkumar** [comment]
@Engineering-Robert This is great. :+1:

**Comment by Engineering-Robert** [comment]
Woo!

**Pull request merged**
