### PR TITLE
Added chainable route handlers for some routes.

### PR DESCRIPTION
**Pull request by SamuelPinho**
Some paths can be specified in just one line.

---
This change is [Reviewable](https://reviewable.io/reviews/vinitkumar/node-twitter/146)

### CODE REVIEW

**Comment by Engineering-Robert** [comment]
Some tests are failing, so I'll clone your branch @SamuelPinho and have a look at what's wrong. I like the idea of making the code more concise with chainable route handlers!

**Comment by Engineering-Robert** [comment]
Oh, I see what the issue is @SamuelPinho. We are currently running Express 3.x and we haven't yet migrated the code to use Expresx 4.x, so we cannot implement chainable routes at the moment. If you end up refactoring the project to use Express 4.x, that would be extremely helpful!

**Comment by Engineering-Robert** [comment]
That's awesome! Thanks a lot @SamuelPinho. Looking forward to your next PR!

**Comment by vinitkumar** [comment]
@SamuelPinho Have you already ported to the code to express-4 in your fork?

**Pull request closed without merging**
