### PR TITLE
Controller promises

### PR DESCRIPTION
**Pull request by vinitkumar**
This change is [Reviewable](https://reviewable.io/reviews/vinitkumar/node-twitter/137)

### CODE REVIEW

**Comment by Engineering-Robert** [comment]
Fixes #115

**Comment by vinitkumar** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/models/user.js, line 98 at r1](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137#-KutsruXCa4aWTzHrN8B:-KutsruXCa4aWTzHrN8C:b-dp7swn) ([raw file](https://github.com/vinitkumar/node-twitter/blob/f4d719d66c255a1109c59319cc9899a3b6ca01b0/app/models/user.js#L98)):*
> ```JavaScript
>   list: function(options) {
>     const criteria = options.criteria || {};
>     return this.find(criteria)
> ```

This change breaks the user API and hence it breaks the tests as well. If you go to /apiv1/users, it takes a lot of time to return response. This is a breaking change. We can't have any breaking change.

---

*[test/test.js, line 23 at r1](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137#-KuttB5APP7nliimKGyd:-KuttB5B56K0s5a9J4uw:bot0mxt) ([raw file](https://github.com/vinitkumar/node-twitter/blob/f4d719d66c255a1109c59319cc9899a3b6ca01b0/test/test.js#L23)):*
> ```JavaScript
> 
> 
> // describe('Test Users API', function (done) {
> ```

Please never comment tests. If the tests are failing, it means something is not working as it is supposed to be. Your changes broken users and tweets API, hence these two tests failed.

---

*[test/test.js, line 53 at r1](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137#-KuttPXIiBaXXJGvUAPa:-KuttPXIiBaXXJGvUAPb:bot0mxt) ([raw file](https://github.com/vinitkumar/node-twitter/blob/f4d719d66c255a1109c59319cc9899a3b6ca01b0/test/test.js#L53)):*
> ```JavaScript
> //     request(app)
> //     .get('/apiv1/tweets')
> //     .expect(200)
> ```

Please never comment tests. If the tests are failing, it means something is not working as it is supposed to be. Your changes broken users and tweets API, hence these two tests failed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137)*

**Comment by vinitkumar** [comment]
@Engineering-Robert Also, please refer this. Getting rid of callbacks is fine but the promise must be used in a proper way. The beauty of JS is async, it can be achieved using callbacks/promises but if done incorrectly, it would become blocking. Just as in this case, tweet and user API have blocking query.

**Comment by Engineering-Robert** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/models/user.js, line 98 at r1](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137#-KutsruXCa4aWTzHrN8B:-Kutuh73_fCjbwQHPACd:b-2lndmm) ([raw file](https://github.com/vinitkumar/node-twitter/blob/f4d719d66c255a1109c59319cc9899a3b6ca01b0/app/models/user.js#L98)):*
<details><summary><i>Previously, vinitkumar (Vinit Kumar) wrote…</i></summary><blockquote>

This change breaks the user API and hence it breaks the tests as well. If you go to /apiv1/users, it takes a lot of time to return response. This is a breaking change. We can't have any breaking change.
</blockquote></details>

That is because I did not refactor the API controllers to use Promises. We aren't using the API controllers, so that is why I did not bother refactoring that code.

---

*[test/test.js, line 23 at r1](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137#-KuttB5APP7nliimKGyd:-Kutu3eU6Ocuap8McZx-:b-xbzvew) ([raw file](https://github.com/vinitkumar/node-twitter/blob/f4d719d66c255a1109c59319cc9899a3b6ca01b0/test/test.js#L23)):*
<details><summary><i>Previously, vinitkumar (Vinit Kumar) wrote…</i></summary><blockquote>

Please never comment tests. If the tests are failing, it means something is not working as it is supposed to be. Your changes broken users and tweets API, hence these two tests failed.
</blockquote></details>

We aren't using the Tweets API, so i'm not sure why we would want a test for it.

---

*[test/test.js, line 53 at r1](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137#-KuttPXIiBaXXJGvUAPa:-KutuSS5DUYpWsywZ--r:bl5sajb) ([raw file](https://github.com/vinitkumar/node-twitter/blob/f4d719d66c255a1109c59319cc9899a3b6ca01b0/test/test.js#L53)):*
<details><summary><i>Previously, vinitkumar (Vinit Kumar) wrote…</i></summary><blockquote>

Please never comment tests. If the tests are failing, it means something is not working as it is supposed to be. Your changes broken users and tweets API, hence these two tests failed.
</blockquote></details>

We aren't using the Users or Tweets APIs yet, so i'm not sure why we would want a test for them. That is the reason I commented them out, since we can uncomment them when we have implemented the feature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137)*

**Comment by Engineering-Robert** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137)*

**Comment by vinitkumar** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/models/user.js, line 98 at r1](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137#-KutsruXCa4aWTzHrN8B:-Kutw14IrxiCk78HPjCh:b-mm19zt) ([raw file](https://github.com/vinitkumar/node-twitter/blob/f4d719d66c255a1109c59319cc9899a3b6ca01b0/app/models/user.js#L98)):*
<details><summary><i>Previously, Engineering-Robert (Robert Cooper) wrote…</i></summary><blockquote>

That is because I did not refactor the API controllers to use Promises. We aren't using the API controllers, so that is why I did not bother refactoring that code.
</blockquote></details>

Please refactor this code as well.  It is on my todo list to use in future. I don't want to discard it

---

*[test/test.js, line 23 at r1](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137#-KuttB5APP7nliimKGyd:-KutwHybdS16fq3HxUtO:b-mm19zt) ([raw file](https://github.com/vinitkumar/node-twitter/blob/f4d719d66c255a1109c59319cc9899a3b6ca01b0/test/test.js#L23)):*
<details><summary><i>Previously, Engineering-Robert (Robert Cooper) wrote…</i></summary><blockquote>

We aren't using the Tweets API, so i'm not sure why we would want a test for it.
</blockquote></details>

Please refactor this code as well.  It is on my todo list to use in future. I don't want to discard it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137)*

**Comment by Engineering-Robert** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137)*

**Comment by vinitkumar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/test.js, line 53 at r1](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137#-KuttPXIiBaXXJGvUAPa:-Kuu-xkQcNQxbJfPYm08:b-896fix) ([raw file](https://github.com/vinitkumar/node-twitter/blob/f4d719d66c255a1109c59319cc9899a3b6ca01b0/test/test.js#L53)):*
<details><summary><i>Previously, Engineering-Robert (Robert Cooper) wrote…</i></summary><blockquote>

We aren't using the Users or Tweets APIs yet, so i'm not sure why we would want a test for them. That is the reason I commented them out, since we can uncomment them when we have implemented the feature.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinitkumar/node-twitter/137)*

**Pull request merged**
